lohbs_pick/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.main, name="main"),
    path('accounts/', include('allauth.urls')),
    path('users/', include('users.urls')),
    path('products/', include('products.urls')),
    path('picks/', include('picks.urls')),
    path('orders/', include('orders.urls')),
    path('personal_data/', views.personal_data, name="personal_data"),
    path('service_terms/', views.service_terms, name="service_terms"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from .views import *

app_name ="orders"
urlpatterns = [
    path('', main, name="main"),
    path('<int:id>/new/', new, name="new"),
    path('create/', create, name="create")
]

picks/urls.py
from django.urls import path
from . import views

app_name ="picks"
urlpatterns = [
    path('lohbs_pick/', views.lohbs_pick, name="lohbs_pick"),
    path('delete/<int:collection_id>/', views.delete, name="delete"),
    path('delete_cp/<int:cp_id>/<int:collection_id>/', views.delete_cp, name="delete_cp"),
    path('collection_add/', views.collection_add, name="collection_add"),
    path('create_cp/<int:product_id>/', views.create_cp, name="create_cp"),
    path('collection_update/<int:collection_id>/', views.collection_update, name="collection_update"),

    ## 공유 관련
    path('shared/', views.shared, name="shared"),
    path('<int:collection_id>/share/', views.share_new, name="share_new"),
    path('create/', views.share_create, name="share_create"),
    path('<int:id>/edit/', views.share_edit, name="share_edit"),
    path('<int:id>/update/', views.share_update, name="share_update"),
    path('<int:id>/delete/', views.share_delete, name="share_delete"),
]

orders/models.py
from django.db import models
from django.contrib.auth.models import User
from products.models import *
from picks.models import *
from django.utils.translation import ugettext_lazy as _

class OrderProduct(models.Model):
    product = models.ForeignKey(Product, verbose_name=_('상품'), on_delete=models.SET_NULL, null=True)
    quantity = models.PositiveSmallIntegerField(_('수량'))
    price = models.PositiveIntegerField(_('가격'))
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name='주문상품'
        verbose_name_plural='주문상품'
    
    def save(self, *args, **kwargs):
        self.price = self.product.price*self.quantity
        super().save(*args, **kwargs)


class Order(models.Model):
    PERIOD_CHOICES = [
        ("1W", "1주"),
        ("2W", "2주"),
        ("3W", "3주"),
        ("1M", "1달"),
        ("2M", "2달"),
        ("3M", "3달"),
    ]

    user = models.ForeignKey(User, verbose_name=_('사용자'), on_delete=models.CASCADE)
    order_total = models.PositiveIntegerField(_('총 가격'))
    address = models.CharField(_('배송지 주소'), max_length=300)                    
    collection = models.ForeignKey(Collection, verbose_name=_('컬렉션'), on_delete=models.SET_NULL, null=True)
    collection_name = models.CharField(_('컬렉션명'), max_length=100)
    order_products = models.ManyToManyField(OrderProduct, verbose_name=_('주문상품'), related_name="order_products", through="Ordering")
    recipient = models.CharField(_('받는 사람'), max_length=10)
    recipient_phone = models.CharField(_('수령인 연락처'), max_length=15)
    delivery_message = models.TextField(_('배송 요청사항'), blank=True)
    period = models.CharField(_('주기'), max_length=2, choices=PERIOD_CHOICES)
    isValid = models.BooleanField(_('유효성'), default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name='주문'
        verbose_name_plural='주문'


class Ordering(models.Model):
    order = models.ForeignKey(Order, verbose_name=_('주문'), on_delete=models.CASCADE)
    order_product = models.ForeignKey(OrderProduct, verbose_name=_('주문 상품'), on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together=(
            ('order', 'order_product')
        )

picks/models.py
from django.db import models
from django.contrib.auth.models import User
from products.models import *
from django.utils.translation import ugettext_lazy as _

class CollectionProduct(models.Model):
    product = models.ForeignKey(Product, verbose_name=_('상품'), on_delete=models.CASCADE)
    quantity = models.PositiveSmallIntegerField(_('수량'))
    sub_total = models.PositiveIntegerField(_('가격'))
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        verbose_name='컬렉션상품'
        verbose_name_plural='컬렉션상품'

    def save(self, *args, **kwargs):
        self.sub_total = self.product.price*self.quantity
        super().save(*args, **kwargs)


class Collection(models.Model):
    PERIOD_CHOICES = [
        ("1W", "1주"),
        ("2W", "2주"),
        ("3W", "3주"),
        ("1M", "1달"),
        ("2M", "2달"),
        ("3M", "3달"),
    ]   

    user = models.ForeignKey(User, verbose_name=_('사용자'), on_delete=models.CASCADE)
    collection_products = models.ManyToManyField(CollectionProduct, verbose_name=_('컬렉션 상품'), related_name="collection_products", blank=True, through='Collecting')
    collection_total = models.PositiveIntegerField(_('가격'), default=0)
    period = models.CharField(_('배송주기'), max_length=2, choices=PERIOD_CHOICES, blank=True)
    name = models.CharField(_('컬렉션명'), max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name='컬렉션'
        verbose_name_plural='컬렉션'


class Collecting(models.Model):
    collection = models.ForeignKey(Collection, verbose_name= _('컬렉션'), on_delete=models.CASCADE)
    collection_product = models.ForeignKey(CollectionProduct, verbose_name= _('컬렉션 상품'), on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        unique_together=(
            ('collection', 'collection_product')
        )


class Share(models.Model):
    user = models.ForeignKey(User, verbose_name=_('작성자'), on_delete=models.SET_NULL, null=True)
    image = models.ImageField(_('이미지'), upload_to='s_images/')
    content = models.TextField(_('내용'))
    collection_name = models.CharField(_('컬렉션명'), max_length=100)
    collection_products = models.TextField(_('컬렉션 상품'))
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name='공유'
        verbose_name_plural='공유'

lohbs_pick/views.py
from django.shortcuts import render
from products.models import Product
from picks.models import *

def main(request):
    products = Product.objects.all()[0:8]
    shared_lists = Share.objects.all().order_by('-created_at')[0:3]
    return render(request, 'index.html', {"products":products, 'shared_lists':shared_lists})


def personal_data(request):
    return render(request, 'personal_data.html')


def service_terms(request):
    return render(request, 'service_terms.html')

picks/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import *
from products.models import Product
from django.contrib.auth.decorators import login_required
import pdb
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

# 롭스픽 메인
@login_required
def lohbs_pick(request):
    user = request.user
    picks = Collection.objects.filter(user=user).order_by('-created_at')
    return render(request, 'picks/lohbs_pick.html', {'picks':picks} )


# 컬렉션 추가하기
def collection_add(request):
    picks = Collection.objects.filter(user=request.user)
    return render(request, 'picks/choose.html', {'picks':picks})


# 컬렉션 수정하기
def collection_update(request, collection_id):
    pick = get_object_or_404(Collection, pk=collection_id)
    pick.collection_total = 0

    if request.method == "POST":
        name  = request.POST.get('name')
        picks = Collection.objects.filter(user=request.user).order_by('-created_at')
        for c in picks:
            if c == pick:
                continue
            elif c.name == name:
                message = "True"
                return render(request, 'picks/lohbs_pick.html', {'picks':picks, 'message':message})

        period = request.POST.get('period')

        pick.name = name
        pick.period = period

        for i in range(0, len(pick.collection_products.all())):
            key = request.POST.get('num'+str(i))
            quantity = request.POST.get('quantity'+str(i))
            cp = CollectionProduct.objects.get(pk=key)
            cp.quantity = int(quantity)
            cp.sub_total = cp.product.price*cp.quantity
            pick.collection_total += cp.sub_total
            cp.save()

        pick.save()
        return redirect('picks:lohbs_pick')

    return render(request, 'picks/collection_update.html', {'pick':pick})


# 컬렉션 삭제하기
def delete(request, collection_id):
    collection = get_object_or_404(Collection, pk=collection_id)
    collection.delete()
    return redirect('picks:lohbs_pick')


# 컬렉션 상품 삭제하기
def delete_cp(request, cp_id, collection_id):
    collection = get_object_or_404(Collection, pk=collection_id)
    cp = get_object_or_404(CollectionProduct, pk=cp_id)
    collection.collection_products.remove(cp)
    collection.collection_total -= cp.sub_total
    collection.save()
    return redirect('picks:collection_update', collection_id)


# 컬렉션 상품 만들고 컬렉션에 저장
def create_cp(request, product_id):
    if request.user.is_active:
        if request.method == "POST":

            product = get_object_or_404(Product, pk=product_id)
            quantity = request.POST.get('quantity')
            pick = request.POST.get('pick')
            quantity = int(quantity)

            if pick == "new":
                name = request.POST.get('collection_name')
                user = request.user 
                picks = Collection.objects.filter(user=user).order_by('-created_at')
                for c in picks:
                    if c.name == name:
                        message = "True"
                        return render(request, 'picks/lohbs_pick.html', {'picks':picks, 'message':message})
                collection = Collection.objects.create(user=user, name=name)
                
            else:
                collection = get_object_or_404(Collection, pk=pick)

                for collection_product in collection.collection_products.all():
                    if product == collection_product.product:
                        collection.collection_products.remove(collection_product)
                        collection.collection_total -= collection_product.sub_total
                        
            cp = CollectionProduct.objects.create(product=product, quantity=quantity)        
            collection.collection_products.add(cp)
            collection.collection_total += cp.sub_total
            collection.save()

            return redirect('picks:lohbs_pick')      
    else:
      return redirect('account_login')


## 공유 관련
# 공유된 롭스픽 메인 페이지(목록)
def shared(request):
    posts_list = Share.objects.all().order_by('-id')

    page = request.GET.get('page', 1)
    paginator = Paginator(posts_list, 12)
    try:
        posts = paginator.get_page(page)
    except PageNotAnInteger:
        pstss = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    return render(request, 'picks/shared.html', {'posts': posts})


# 롭스픽 공유글 작성 페이지
@login_required
def share_new(request, collection_id):
    collection = get_object_or_404(Collection, pk=collection_id)

    if request.user == collection.user:
        context = {
          'collection_id': collection_id,
          'collection_name': collection.name,
          'collection_products': collection.collection_products.all()
        }
        return render(request, 'picks/share_new.html', context)

    return redirect('picks:lohbs_pick')


# 롭스픽 공유글 생성
@login_required
def share_create(request):
    products_list = []
    user = request.user
    if request.method == "POST":
        c_id = request.POST.get('collection_id')
        collection = get_object_or_404(Collection, pk=c_id)
        c_products = collection.collection_products.all()
        for cp in c_products:
            p = cp.product
            p_str = f"[{p.brand}] {p.name}"
            products_list.append(p_str)

        content = request.POST.get('content')
        collection_name = request.POST.get('collection_name')
        image = request.FILES.get('image')
        products = ', '.join(products_list)

        Share.objects.create(user=user, image=image, content=content, collection_name=collection_name, collection_products=products)
    return redirect('picks:shared')


# 롭스픽 공유글 수정 페이지
@login_required
def share_edit(request, id):
    share = get_object_or_404(Share, pk=id)
    if request.user == share.user:
        products = share.collection_products
        products_list = products.split(', ')

        context = {
          'share': share,
          'products': products_list
        }
        return render(request, 'picks/share_edit.html', context)
    return redirect('picks:shared')


# 롭스픽 공유글 수정
@login_required
def share_update(request, id):
    share = get_object_or_404(Share, pk=id)
    if request.method == "POST":
        image = request.FILES.get('image')
        
        if image :
            share.image = image

        share.content = request.POST.get('content')
        share.save()
    return redirect('picks:shared')


# 롭스픽 공유글 삭제
@login_required
def share_delete(request, id):
    share = get_object_or_404(Share, pk=id)
    if request.user == share.user:
        share.delete()
    return redirect('picks:shared')

picks/templates/picks/collection_update.html
{% extends 'base.html' %}
{% load static %}   
{% load humanize %}
{% block content %}

<link rel="stylesheet" href="{% static 'css/yeonjin.css' %}">
<link rel="stylesheet" href="{% static 'css/breadcrumb.css' %}">

	<!-- ================ start banner area ================= -->	
  <section class="blog-banner-area" id="category">
    <div class="container h-100">
      <div class="blog-banner">
        <div class="text-center breadcrumb-content" style="margin-top: 0;">
          <h2 class="page-title">Edit My LOHB'S Pick</h2>
          <nav aria-label="breadcrumb" class="banner-breadcrumb">
            <ol class="breadcrumb justify-content-center">
              <li class="breadcrumb-item"><a href="{% url 'main' %}"><i class="fas fa-home"></i> Home</a></li>
              <li class="breadcrumb-item active" aria-current="page">Edit My LOHB'S Pick</li>
            </ol>
          </nav>
        </div>
      </div>
    </div>
  </section>
	<!-- ================ end banner area ================= -->
  
  

  <!--================Cart Area =================-->
  <!-- Section -->
  <section class="cart_area">
    <div class="container">
                                
            <!-- Form -->
            <form method="POST" action="{% url 'picks:collection_update' pick.id %}" id="form" class="form">
                {% csrf_token %}
                <div class="mb-20 mb-md-10" style="margin-bottom:20px;">
                    <label>롭스픽 이름 </label>
                    <input type="text" name="name" class="input-md form-control" maxlength="100" value="{{ pick.name }}">
                </div>

                <label>배송주기</label>

                <div class="mb-20 mb-md-10" style="margin-bottom:20px;">
                    <select id="testSelect" name="period" class="form-control input-sm">
                        <option value="1W" selected>1주</option>
                        <option value="2W">2주</option>
                        <option value="3W">3주</option>
                        <option value="1M">1달</option>
                        <option value="2M">2달</option>
                        <option value="3M">3달</option>
                    </select>
                </div>

                <div class="table-responsive" style="padding-top:20px;">
                    <label>상품 목록</label>
                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="col">Product</th>
                                <th scope="col">Quantity</th>
                                <th scope="col"></th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for collection_product in pick.collection_products.all %}
                                <tr>
                                    <td>
                                        <div class="media">
                                            <div class="d-flex" style="margin-right:10px;">
                                                <img src="{{ collection_product.product.image.url }}" width="100px" height="100px"alt="">
                                            </div>
                                            <div class="media-body">
                                                <strong>{{ collection_product.product.brand }}</strong><br>
                                                {{ collection_product.product.name }}
                                            </div>
                                        </div>
                                    </td>
                                    <input type="hidden" name="num{{forloop.counter0}}" value="{{collection_product.id}}">
                                    <td>
                                        <div class="product_count">
                                            <input type="text" name="quantity{{forloop.counter0}}" id="sst{{ forloop.counter0 }}" maxlength="12" value="{{ collection_product.quantity }}" title="Quantity:" class="input-text qty" style="width:50px;height:30px;">
                                            <button onclick="var result = document.getElementById('sst{{ forloop.counter0 }}'); var sst{{ forloop.counter0 }} = result.value; if( !isNaN( sst{{ forloop.counter0 }} )) result.value++;return false;" class="increase items-count" type="button"><i class="fas fa-chevron-up"></i></button>
                                            <button onclick="var result = document.getElementById('sst{{ forloop.counter0 }}'); var sst{{ forloop.counter0 }} = result.value; if( !isNaN( sst{{ forloop.counter0 }} ) &amp;&amp; sst{{ forloop.counter0 }} > 1 ) result.value--;return false;" class="reduced items-count" type="button"><i class="fas fa-chevron-down"></i></button>
                                        </div>
                                    </td>
                                    <!-- <td>
                                        {{ collection_product.sub_total|intcomma }} 원
                                    </td> -->
                                    <td>
                                        <a href="{% url 'picks:delete_cp' collection_product.id  pick.id %}" style="color:gray;"><i class="fas fa-trash-alt" style="font-size:20px;"></i></a>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="container">
                    <button type="submit" class="button button--active button-review">저장</button>
                </div>          
            </form>
            <!-- End Form -->
        </div>
        
</section>
                      
<!-- End Section -->

<script src="{% static 'js/accordion.js' %}"></script>

<script>
    var tmp = "{{ pick.period }}";
    if (tmp) {
        $('#testSelect').val(tmp).prop("selected",true);
    }
</script>

{% endblock %}

<!-- Button trigger modal -->

picks/templates/picks/lohbs_pick.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% block content %}

<link rel="stylesheet" href="{% static 'css/accordion.css' %}">
<link rel="stylesheet" href="{% static 'css/breadcrumb.css' %}">

	<!-- ================ start banner area ================= -->	
  <section class="blog-banner-area" id="category">
    <div class="container h-100">
      <div class="blog-banner">
        <div class="text-center breadcrumb-content" style="margin-top: 0;">
          <h2 class="page-title">My LOHB'S Pick</h2>
          <nav aria-label="breadcrumb" class="banner-breadcrumb">
            <ol class="breadcrumb justify-content-center">
              <li class="breadcrumb-item"><a href="{% url 'main' %}"><i class="fas fa-home"></i> Home</a></li>
              <li class="breadcrumb-item active" aria-current="page">My LOHB'S Pick</li>
            </ol>
          </nav>
        </div>
      </div>
    </div>
  </section>
  <!-- ================ end banner area ================= -->
  
  

  <!--================Cart Area =================-->
  <!-- Section -->
  <section class="cart_area">
    <div class="container">
        
        <div class="row section-text">
            <div class="col-md-8 col-md-offset-2" style="margin:0 auto;">
                
                <!-- Accordion -->
                <dl class="accordion">
                    
                    {% for pick in picks %}
                        <dt>
                            <a class="pb-0" href="#">
                            <p class="mb-0">
                            <h6>{{ pick.name }}</h6>
                            <p class="mb-0 mr-4" align="right"> 배송주기: {% if pick.period %}{{ pick.get_period_display }}{% else %}-{% endif %}</p>
                            <p class="mr-4 mb-1" align="right"> 합계: {{ pick.collection_total | intcomma }}원</p>
                            <p class="mr-4" align="right">
                              {% if not pick.order_set.all %}
                                  <button class="m-0 btn btn-mod btn-small btn-circle" onclick="location.href='{% url 'orders:new' pick.id %}'">주문</button>
                              {% endif %}
                              {% if pick.order_set.all %}
                                  <button class="m-0 btn btn-mod btn-small btn-circle" onclick="location.href='{% url 'picks:share_new' pick.id %}'">공유</button>
                              {% endif %}
                              <button class="m-0 btn btn-mod btn-small btn-circle" style="border-right-width: 0px" onclick="location.href='{% url 'picks:collection_update' pick.id %}'">수정</button>
                              <button class="m-0 btn btn-mod btn-small btn-circle" style="border-right-width: 0px" onclick="location.href='{% url 'picks:delete' pick.id %}'">삭제</button>
                            </p>
                            </p>
                            </a>
                        </dt>
                        {% if pick.collection_products.exists %}
                            <dd class="px-0 py-0" style="border: 1px solid #ddd;">
                                <div class="table-responsive">
                                    <table class="table">
                                        <thead>
                                            <tr>
                                                <th scope="col"></th>
                                                <th scope="col">Product</th>
                                                <th scope="col">Price</th>
                                                <th scope="col">Quantity</th>
                                                <th scope="col"></th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for collection_product in pick.collection_products.all %}
                                                <tr>
                                                    <td>
                                                        <div class="media">
                                                            <div class="d-flex">
                                                                <img src="{{ collection_product.product.image.url }}" width="100px" height="100px" alt="">
                                                            </div>
                                                        </div>
                                                    </td>
                                                    <td>
                                                    <strong>{{ collection_product.product.brand }}</strong><br>
                                                    {{ collection_product.product.name }}
                                                    </td>
                                                    <td>
                                                    {{ collection_product.product.price | intcomma }}원
                                                    </td>
                                                    <td>
                                                    <div class="product_count">
                                                        {{ collection_product.quantity }}개
                                                    </div>
                                                    </td>
                                                    <td>
                                                    <!-- <a href="{% url 'picks:delete_cp' collection_product.id  pick.id %}"><i class="fas fa-trash-alt" style="font-size:20px;"></i></a> -->
                                                    </td>
                                                </tr>
                                            {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </dd>
                        {% endif %}
                    {% endfor %}
                </dl>
                <!-- End Accordion -->
            </div>
        </div>
    </div>
</section> 
<!-- End Section -->

<script src="{% static 'js/accordion.js' %}"></script>

<script>
    var tmp = "{{ message }}";
    if (tmp) {
        alert("해당 이름을 가진 롭스픽이 존재합니다.\n롭스픽 이름은 중복될 수 없습니다.");
    }
</script>

{% endblock %}

<!-- Button trigger modal -->

picks/templates/picks/share_edit.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <!-- 롭스픽 공유글 수정 페이지 -->
    <link rel="stylesheet" href="{% static 'css/breadcrumb.css' %}">

    <style>
      .td-last {
        border-bottom: 1px solid #dee2e6;
      }
    </style>

    <!-- ================ start banner area ================= -->	
    <section class="blog-banner-area" id="category">
      <div class="container h-100">
        <div class="blog-banner">
          <div class="text-center breadcrumb-content" style="margin-top: 0;">
            <h2 class="page-title">Share My LOHB'S Pick</h2>
            <nav aria-label="breadcrumb" class="banner-breadcrumb">
              <ol class="breadcrumb justify-content-center">
                <li class="breadcrumb-item"><a href="{% url 'main' %}"><i class="fas fa-home"></i> Home</a></li>
                <li class="breadcrumb-item active" aria-current="page">Share My LOHB'S Pick</li>
              </ol>
            </nav>
          </div>
        </div>
      </div>
    </section>
    <!-- ================ end banner area ================= -->

    <!--================ Share Area =================-->
    <section class="checkout_area section-margin--small">
        <div class="container">
            <div class="billing_details">
                <div class="row">
                    <div class="col-lg-12">
                        <h3>Collection Information</h3>
                        <form class="row contact_form" action="{% url 'picks:share_update' share.id  %}" method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            <input type="hidden" name="collection_id" value="collection_id">
                            <div class="col-md-12 form-group">
                                <input type="text" class="form-control" id="zip" name="collection_name" value="{{ share.collection_name }}" readonly>
                            </div>
                            <div class="col-md-12 table-responsive">
                                <table class="table">
                                    <tbody>
                                        {% for p in products %}
                                        <tr class="td-last">
                                            <td>
                                                <span>{{ p }}</span>
                                            </td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                            <div class="col-md-12 form-group mb-0">
                                <div class="creat_account" id="file-content">
                                    <h3>How was your collection?</h3>
                                </div>
                                <div class="custom-file">
                                    <input type="file" class="custom-file-input" id="imageInput" name="image" accept="image/*" onchange="filePreview(this)">
                                    <label class="custom-file-label" id="imageInputLabel" for="imageInput">{{ share.image.url }}</label>
                                </div>
                                <img src="data:," style="width: 50%" id="show-image-tag" alt>
                                <textarea class="form-control" name="content" id="message" rows="1" placeholder="컬렉션에 대한 후기를 작성해 주세요!" required>{{ share.content }}</textarea>
                            </div>
                            <div class="form-group text-center text-md-right mt-3">
                                <button type="submit" class="button button--active button-review">등록하기</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--================ End Share Area =================-->

    <script src="{% static 'js/share-edit.js' %}"></script>
    <script src="{% static 'js/share.js' %}"></script>
    <script>
      $(".custom-file-input").on("change", function() {
        var fileName = $(this).val().split("\\").pop();
        $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
      });
    </script>
{% endblock %}