lohbs_pick/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.main, name="main"),
    path('accounts/', include('allauth.urls')),
    path('users/', include('users.urls')),
    path('products/', include('products.urls')),
    path('picks/', include('picks.urls')),
    path('orders/', include('orders.urls')),
    path('personal_data/', views.personal_data, name="personal_data"),
    path('service_terms/', views.service_terms, name="service_terms"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

picks/urls.py
from django.urls import path
from . import views

app_name ="picks"
urlpatterns = [
    path('lohbs_pick/', views.lohbs_pick, name="lohbs_pick"),
    path('delete/<int:collection_id>/', views.delete, name="delete"),
    path('delete_cp/<int:cp_id>/<int:collection_id>/', views.delete_cp, name="delete_cp"),
    path('collection_add/', views.collection_add, name="collection_add"),
    path('create_cp/<int:product_id>/', views.create_cp, name="create_cp"),
    path('collection_update/<int:collection_id>/', views.collection_update, name="collection_update"),

    ## 공유 관련
    path('shared/', views.shared, name="shared"),
    path('<int:collection_id>/share/', views.share_new, name="share_new"),
    path('create/', views.share_create, name="share_create"),
    path('<int:id>/edit/', views.share_edit, name="share_edit"),
    path('<int:id>/update/', views.share_update, name="share_update"),
    path('<int:id>/delete/', views.share_delete, name="share_delete"),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"
urlpatterns = [
    path('<int:id>/', views.main, name="main"),
    path('edit/<int:id>/', views.edit, name="edit"),
    path('update/<int:id>/', views.update, name="update"),
    path('schedule/<int:id>/', views.schedule, name="schedule"),
]

users/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User
from products.models import *
from django.db.models.signals import post_save
from django.dispatch import receiver


class Profile(models.Model):
    user = models.OneToOneField(User, verbose_name=_('사용자'), on_delete=models.CASCADE)
    nickname = models.CharField(_('닉네임'), max_length=10, unique=True)
    profile_image = models.ImageField(_('프로필 이미지'), upload_to="profile_images/", default="images/default_profile.jpg")
    profile_address = models.CharField(_('프로필 주소'), max_length=300)
    phone = models.CharField(_('연락처'), max_length=20)
    address1 = models.CharField(_('주소1'), max_length=300)
    address2 = models.CharField(_('주소2 참고항목'), max_length=300)
    detail_address = models.CharField(_('상세주소'), max_length=300)
    zipcode = models.CharField(_('우편번호'), max_length=5)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name ='프로필'
        verbose_name_plural ='프로필'

        
@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

users/forms.py
from allauth.account.forms import SignupForm
from django import forms

    
class MyCustomSignupForm(SignupForm):
    nickname = forms.CharField(label='닉네임', widget=forms.TextInput(attrs={'placeholder': '닉네임'}))

    def save(self, request):
        user = super(MyCustomSignupForm, self).save(request)
        user.profile.nickname = self.cleaned_data['nickname']
        user.save()
        return user
        

users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import *
import json, datetime
from orders.models import *
import pdb

# 프로필 페이지
def main(request, id):
    user_profile = get_object_or_404(User, pk=id)

    if request.user == user_profile:
        return render(request, 'users/main.html', {'user_profile': user_profile})
    return redirect('main')

# 캘린더 페이지
def schedule(request, id):
    current_user = request.user
    user = get_object_or_404(User, pk=id)
    
    if user == request.user:
        all_orders = Order.objects.filter(user=user).filter(isValid=True)
        orders_list = []

        for order in all_orders:
            parsed_date = order.created_at.strftime(f'%Y-%m-%d')
            orders_list.append({
              "title": order.collection_name,
              "start": parsed_date,
              "period":order.period,
            },)

        jsonString = json.dumps(orders_list) # json 변환

        return render(request, 'users/schedule.html', {'all_orders':jsonString})
    return redirect('users:schedule', current_user.id)

# 프로필 수정 페이지
@login_required
def edit(request, id):
    current_user = request.user
    user = get_object_or_404(User, pk=id)

    if user == current_user:
        if user.username == 'testuser':
            return redirect('users:main', current_user.id)
        else:
            return render(request, 'users/edit.html', {'user': user})
    else:
        return redirect('users:main', current_user.id)


# 프로필 수정
@login_required
def update(request, id):
    if request.method == "POST":
        user = get_object_or_404(User, pk=id)
        nickname = request.POST.get('nickname')
        phone = request.POST.get('phone')
        profile_address = request.POST.get('profile_address')
        
        if request.FILES.get('profile_image'):
            user.profile.profile_image = request.FILES.get('profile_image')
            
        if request.POST.get('checkbox'):
            user.profile.profile_image = 'images/default_profile.jpg'


        user.profile.nickname = nickname
        user.profile.phone = phone
        user.profile.profile_address = profile_address

        user.profile.address1 = request.POST.get('b')
        user.profile.address2 = request.POST.get('d')
        user.profile.detail_address = request.POST.get('c')
        user.profile.zipcode = request.POST.get('a')

        user.profile.save()
        return redirect('users:main', id)

users/templates/users/edit.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<script src="https://t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js"></script>
<script>
	function sub(){
		a=document.form.a.value;
		b=document.form.b.value;
		c=document.form.c.value;
		d=document.form.d.value;
		e=a+" "+b+" "+c+" "+d;
		document.form.profile_address.value=e;

		document.form.submit();
	}
	
    function sample6_execDaumPostcode() {
        new daum.Postcode({
            oncomplete: function(data) {
                // 팝업에서 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분.

                // 각 주소의 노출 규칙에 따라 주소를 조합한다.
                // 내려오는 변수가 값이 없는 경우엔 공백('')값을 가지므로, 이를 참고하여 분기 한다.
                var addr = ''; // 주소 변수
                var extraAddr = ''; // 참고항목 변수

                //사용자가 선택한 주소 타입에 따라 해당 주소 값을 가져온다.
                if (data.userSelectedType === 'R') { // 사용자가 도로명 주소를 선택했을 경우
                    addr = data.roadAddress;
                } else { // 사용자가 지번 주소를 선택했을 경우(J)
                    addr = data.jibunAddress;
                }

                // 사용자가 선택한 주소가 도로명 타입일때 참고항목을 조합한다.
                if(data.userSelectedType === 'R'){
                    // 법정동명이 있을 경우 추가한다. (법정리는 제외)
                    // 법정동의 경우 마지막 문자가 "동/로/가"로 끝난다.
                    if(data.bname !== '' && /[동|로|가]$/g.test(data.bname)){
                        extraAddr += data.bname;
                    }
                    // 건물명이 있고, 공동주택일 경우 추가한다.
                    if(data.buildingName !== '' && data.apartment === 'Y'){
                        extraAddr += (extraAddr !== '' ? ', ' + data.buildingName : data.buildingName);
                    }
                    // 표시할 참고항목이 있을 경우, 괄호까지 추가한 최종 문자열을 만든다.
                    if(extraAddr !== ''){
                        extraAddr = ' (' + extraAddr + ')';
                    }
                    // 조합된 참고항목을 해당 필드에 넣는다.
                    document.getElementById("sample6_extraAddress").value = extraAddr;
                
                } else {
                    document.getElementById("sample6_extraAddress").value = '';
                }

                // 우편번호와 주소 정보를 해당 필드에 넣는다.
                document.getElementById('sample6_postcode').value = data.zonecode;
                document.getElementById("sample6_address").value = addr;
                // 커서를 상세주소 필드로 이동한다.
                document.getElementById("sample6_detailAddress").focus();
            }
        }).open();
    }
</script>

<link rel="stylesheet" href="{% static 'css/breadcrumb.css' %}">
<style>
  .set-inline {
    display: inline!important;
  }
</style>

<!-- ================ start banner area ================= -->	
<section class="blog-banner-area" id="category">
  <div class="container h-100">
    <div class="blog-banner">
      <div class="text-center breadcrumb-content" style="margin-top: 0;">
        <h2 class="page-title">Edit Profile</h2>
        <nav aria-label="breadcrumb" class="banner-breadcrumb">
          <ol class="breadcrumb justify-content-center">
            <li class="breadcrumb-item"><a href="{% url 'main' %}"><i class="fas fa-home"></i> Home</a></li>
            <li class="breadcrumb-item active" aria-current="page">Edit Profile</li>
          </ol>
        </nav>
      </div>
    </div>
  </div>
</section>
<!-- ================ end banner area ================= -->

<!--================Product Description Area =================-->
<section class="product_description_area">
	<div class="container">
				<div class="row">
					<div class="review_box col-lg-12">
            <div class="billing_details">
              <div class="row">
                  <div class="col-lg-12">
                      <h3 style="margin-bottom: 0;">Edit Profile</h3>
                  </div>
              </div>
            </div>
						<form class="row contact_form" action="{% url 'users:update' user.pk %}" method="POST" enctype="multipart/form-data" id="contactForm" novalidate="novalidate" name="form" onSubmit="return sub()">
							{% csrf_token %}
							<div class="col-lg-6">
								<div class="user-name">
									<label>프로필사진</label>
                </div>
                <div class="custom-file">
                  <input type="file" class="custom-file-input" id="imageInput" name="profile_image" accept="image/*" onchange="filePreview(this)" style="margin:0 auto;">
                  <label class="custom-file-label" id="imageInputLabel" for="imageInput">
                    {% if user.profile.profile_image %}
                    {{ user.profile.profile_image.url }}
                    {% endif %}
                  </label>
                </div>
                <div class="mt-2">
                  <input type="checkbox" name="checkbox" value="1">
                  <label class="mt-10">기본 이미지로 변경하기</label>
                </div>
                <img src="data:," style="width: 50%" id="show-image-tag" alt>
							</div>
							<div class="col-lg-6">
								<div class="col-md-12">
									<label>닉네임</label>
									<div class="form-group">
										<input type="text" class="form-control" name="nickname" value="{{ user.profile.nickname }}">
									</div>
								</div>
								<div class="col-md-12">
									<label>연락처</label>
									<div class="form-group">
										<input type="text" class="form-control phone" name="phone" value="{{ user.profile.phone }}" maxlength="13">
									</div>
								</div>
								<div class="col-md-12">
									<label>주소</label>
									<div class="form-group">
										<input type="text" class="form-control col-md-8 set-inline" name="a" id="sample6_postcode" placeholder="우편번호가 들어가는 자리입니다." value="{{ user.profile.zipcode }}" readonly>
										<input type="button" class="col-md-3 set-inline mb-2" onclick="sample6_execDaumPostcode()" value="우편번호 찾기"><br>
										<input type="text" class="form-control mb-2" name ="b" id="sample6_address" placeholder="주소가 들어가는 자리입니다." value="{{ user.profile.address1 }}" readonly>
										<input type="text" class="form-control col-md-8 set-inline" name="c" id="sample6_detailAddress" placeholder="상세주소를 입력해주세요." value="{{ user.profile.detail_address }}">
										<input type="text" class="form-control col-md-3 set-inline" name="d" id="sample6_extraAddress" value="{{ user.profile.address2 }}" readonly>
										<input type="hidden" class="form-control" name="profile_address" value="{{ user.profile.profile_address }}">
									</div>
								</div>
								<div class="col-md-12 text-right" style="margin-top: 50px;">
									<button type="submit" value="수정" class="btn primary-btn" onClick="sub()">수정</button>
								</div>
							</div>
						</form>
					</div>
				</div>
	</div>
</section>

<script src="{% static 'js/share-edit.js' %}"></script>
<script src="{% static 'js/share.js' %}"></script>
<script>
  $(".custom-file-input").on("change", function() {
    var fileName = $(this).val().split("\\").pop();
    $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
  });

  $('.phone').keydown(function(event) {
    var key = event.charCode || event.keyCode || 0;
    $text = $(this);
    if (key !== 8 && key !== 9) {
      if ($text.val().length === 3) {
        $text.val($text.val() + '-');
      }
      if ($text.val().length === 8) {
        $text.val($text.val() + '-');
      }
    }
 
    return (key == 8 || key == 9 || key == 46 || (key >= 48 && key <= 57) || (key >= 96 && key <= 105));          
  });

</script>

{% endblock %}
<!--================End Product Description Area =================-->

users/templates/users/main.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/breadcrumb.css' %}">

<style>
  @media (min-width: 1000px) {
    .product_image_area {
        padding-bottom: 100px;
    }
  }
</style>
	
	<!-- ================ start banner area ================= -->	
  <section class="blog-banner-area" id="category">
    <div class="container h-100">
      <div class="blog-banner">
        <div class="text-center breadcrumb-content" style="margin-top: 0;">
          <h2 class="page-title">MyPage</h2>
          <nav aria-label="breadcrumb" class="banner-breadcrumb">
            <ol class="breadcrumb justify-content-center">
              <li class="breadcrumb-item"><a href="{% url 'main' %}"><i class="fas fa-home"></i> Home</a></li>
              <li class="breadcrumb-item active" aria-current="page">MyPage</li>
            </ol>
          </nav>
        </div>
      </div>
    </div>
  </section>
	<!-- ================ end banner area ================= -->

  <!--================Single Product Area =================-->
	<div class="product_image_area">
		<div class="container">
			<div class="row s_product_inner">
				<div class="col-lg-6">
					<div class="owl-carousel owl-theme s_Product_carousel">
						<div class="single-prd-item">
							<img class="img-fluid" src="{{ user_profile.profile.profile_image.url }}" alt="">
						</div>
						<!-- <div class="single-prd-item">
							<img class="img-fluid" src="img/category/s-p1.jpg" alt="">
						</div>
						<div class="single-prd-item">
							<img class="img-fluid" src="img/category/s-p1.jpg" alt="">
						</div> -->
					</div>
				</div>
				<div class="col-lg-5 offset-lg-1" style="padding-bottom: 50px;">
          <table class="table table-borderless">
            <tr>
              <th><span>ID</span></th>
              <td><span>{{ user_profile.username }}</span></td>
            </tr>
            <tr>
              <th><span>Nickname</span></th>
              <td><span>{{ user_profile.profile.nickname }}</span></td>
            </tr>
            <tr>
              <th><span>Phone</span></th>
              <td><span>{{ user_profile.profile.phone }}</span></td>
            </tr>
            <tr>
              <th><span>Address</span></th>
              <td><span>{{ user_profile.profile.profile_address }}</span></td>
            </tr>
          </table>
          {% if user.username == user_profile.username %}
            {% if user.username == 'testuser' %}
                <div>* 테스트 계정은 회원정보 수정이 불가합니다.</div>
            {% else %}
                <div class="product_count">
                  <a class="button primary-btn" href="{% url 'users:edit' user_profile.id %}">회원정보 수정</a>
                </div>
            {% endif %}
          {% endif %}
				</div>
			</div>
		</div>
	</div>
  <!--================End Single Product Area =================-->

{% endblock %}

users/templates/users/schedule.html
{% extends 'base.html' %}
{% load static %}
{% block extrahead %}

<link rel="stylesheet" href="{% static 'css/breadcrumb.css' %}">
<link href="{% static 'packages/core/main.css' %}" rel='stylesheet' />
<link href="{% static 'packages/daygrid/main.css' %}" rel='stylesheet' />
<script src="{% static 'packages/core/main.js' %}"></script>
<script src="{% static 'packages/interaction/main.js' %}"></script>
<script src="{% static 'packages/daygrid/main.js' %}"></script>
<script>
    all_orders = `{{ all_orders|safe }}`;
    const obj = JSON.parse(all_orders);

    var now = new Date();

    var year= now.getFullYear();
    var mon = (now.getMonth()+1)>9 ? ''+(now.getMonth()+1) : '0'+(now.getMonth()+1);
    var day = now.getDate()>9 ? ''+now.getDate() : '0'+now.getDate();
              
    var today = year + '-' + mon + '-' + day
    
    results = []
    for (var i in obj)
    { 
        var date = new Date(obj[i]['start']);
        var d = date.getDate();
        var m = date.getMonth();
        var y = date.getFullYear();
        for (var j=0; j<12; j++)
        {
            results.push({"title":obj[i]['title'], "start":new Date(y,m,d), "textColor": "white", "color":"#ff530f"});
            if(obj[i]['period']=="1W")
            {
                d=d+7;
            }
            else if(obj[i]['period']=="2W")
            {
                d=d+14;
            }
            else if(obj[i]['period']=="3W")
            {
                d=d+21;
            }
            else if(obj[i]['period']=="1M")
            {
                m=m+1;
            }
            else if(obj[i]['period']=="2M")
            {
                m=m+2;
            }
            else if(obj[i]['period']=="3M")
            {
                m=m+3;
            }

        }
    }
    
    document.addEventListener('DOMContentLoaded', function() {
    var calendarEl = document.getElementById('calendar');
    
    var calendar = new FullCalendar.Calendar(calendarEl, {
      plugins: [ 'interaction', 'dayGrid' ],
      header: {
        left: 'prev,next today',
        center: 'title',
        right: 'dayGridMonth'
      },
      defaultDate: today,
      displayEventTime: false,
      navLinks: true, // can click day/week names to navigate views
      editable: false,
      eventLimit: true, // allow "more" link when too many events
      events: results,
      eventContent: function(arg) {
                let arrayOfDomNodes = []
                // title event
                let titleEvent = document.createElement('div')
                if(arg.event._def.title) {
                  titleEvent.innerHTML = arg.event._def.title
                  titleEvent.classList = "fc-event-title fc-sticky"
                }
    
                // image event
                let imgEventWrap = document.createElement('div')
                if(arg.event.extendedProps.image_url) {
                  let imgEvent = '<img src="'+arg.event.extendedProps.image_url+'" >'
                  imgEventWrap.classList = "fc-event-img"
                  imgEventWrap.innerHTML = imgEvent;
                }
    
                arrayOfDomNodes = [ titleEvent,imgEventWrap ]
    
                return { domNodes: arrayOfDomNodes }
              },
    });

    calendar.render();
  });

</script>
<style>

  body {
    margin: 40px 10px;
    padding: 0;
    font-family: Arial, Helvetica Neue, Helvetica, sans-serif;
    font-size: 14px;
  }

  #calendar {
    max-width: 900px;
    margin: 0 auto;
  }

</style>
{% endblock %}

{% block content %}
	<!-- ================ start banner area ================= -->	
  <section class="blog-banner-area" id="category" style="margin-bottom: 100px;">
    <div class="container h-100">
      <div class="blog-banner">
        <div class="text-center breadcrumb-content" style="margin-top: 0;">
          <h2 class="page-title">Schedule</h2>
          <nav aria-label="breadcrumb" class="banner-breadcrumb">
            <ol class="breadcrumb justify-content-center">
              <li class="breadcrumb-item"><a href="{% url 'main' %}"><i class="fas fa-home"></i> Home</a></li>
              <li class="breadcrumb-item active" aria-current="page">Schedule</li>
            </ol>
          </nav>
        </div>
      </div>
    </div>
  </section>
	<!-- ================ end banner area ================= -->


  <div id='calendar' style="margin-bottom: 100px;"></div>

{% endblock %}