lohbs_pick/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.main, name="main"),
    path('accounts/', include('allauth.urls')),
    path('users/', include('users.urls')),
    path('products/', include('products.urls')),
    path('picks/', include('picks.urls')),
    path('orders/', include('orders.urls')),
    path('personal_data/', views.personal_data, name="personal_data"),
    path('service_terms/', views.service_terms, name="service_terms"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from .views import *

app_name ="orders"
urlpatterns = [
    path('', main, name="main"),
    path('<int:id>/new/', new, name="new"),
    path('create/', create, name="create")
]

picks/urls.py
from django.urls import path
from . import views

app_name ="picks"
urlpatterns = [
    path('lohbs_pick/', views.lohbs_pick, name="lohbs_pick"),
    path('delete/<int:collection_id>/', views.delete, name="delete"),
    path('delete_cp/<int:cp_id>/<int:collection_id>/', views.delete_cp, name="delete_cp"),
    path('collection_add/', views.collection_add, name="collection_add"),
    path('create_cp/<int:product_id>/', views.create_cp, name="create_cp"),
    path('collection_update/<int:collection_id>/', views.collection_update, name="collection_update"),

    ## 공유 관련
    path('shared/', views.shared, name="shared"),
    path('<int:collection_id>/share/', views.share_new, name="share_new"),
    path('create/', views.share_create, name="share_create"),
    path('<int:id>/edit/', views.share_edit, name="share_edit"),
    path('<int:id>/update/', views.share_update, name="share_update"),
    path('<int:id>/delete/', views.share_delete, name="share_delete"),
]

products/urls.py
from django.urls import path
from . import views

app_name ="products"
urlpatterns = [
    path('', views.main, name="main"),
    path('search/', views.search, name="search"),
    path('category_list/', views.category_list, name="category_list"),
    # path('collection_add/<int:product_id>/<int:collection_id>/', views.collection_add, name="collection_add"),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"
urlpatterns = [
    path('<int:id>/', views.main, name="main"),
    path('edit/<int:id>/', views.edit, name="edit"),
    path('update/<int:id>/', views.update, name="update"),
    path('schedule/<int:id>/', views.schedule, name="schedule"),
]

templates/shared/_footer.html
{% load static %}

<style>
    .developers-name {
        color: #7b838a;
        font-family: "Roboto",sans-serif;
    }

    .developers-name:hover {
        color: #ff530f;
    }

    .footer-bottom .footer-text a {
      color: #fff;
      opacity: 1;
    }
</style>

<!--================ Start footer Area  =================-->	
<footer class="footer">
    <div class="footer-area">
        <div class="container">
            <div class="row section_gap">
                <div class="col-lg-3 col-md-6 col-sm-6">
                    <div class="single-footer-widget tp_widgets">
                        <h4 class="footer_title large_title" style="font-family:'LotteMartHappy';">Our Services</h4>
                        <p>
                          여러분이 사용하고 있는 화장품, 매번 드럭스토어나 로드샵을 방문하기 귀찮지 않으신가요?
                        </p>
                        <p>
                          롭스의 다양한 브랜드 제품을 활용해 여러분의 롭스픽을 만들어보세요! 원하는 주기마다 여러분이 담아둔 컬렉션을 정기배송 받을 수 있습니다.
                        </p>
                    </div>
                </div>
                <div class="offset-lg-1 col-lg-2 col-md-6 col-sm-6">
                    <div class="single-footer-widget tp_widgets">
                        <h4 class="footer_title" style="font-family:'LotteMartHappy';">Quick Links</h4>
                        <ul class="list" >
                            <li ><a href="{% url 'main' %}">Home</a></li>
                            <li><a href="{% url 'products:main' %}">Shop</a></li>
                            <li><a href="{% url 'orders:main' %}">Orders</a></li>
                            <li><a href="{% url 'picks:lohbs_pick' %}">LOHB'S Pick</a></li>
                            <li><a href="{% url 'picks:shared' %}">Shared</a></li>
                            <li>
                                {% if user.is_authenticated %}
                                    <a href="{% url 'users:main' user.id %}">Mypage</a>
                                {% else %}
                                    <a href="{% url 'account_login' %}">Mypage</a>
                                {% endif %}
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-6 col-md-6 col-sm-6">
                    <div class="single-footer-widget instafeed">
                        <h4 class="footer_title" style="font-family:'LotteMartHappy';">Developers</h4>
                        <ul class="list instafeed d-flex flex-wrap">
                            <li>
                                <a href="https://github.com/ygk313" target="_blank" class="developers-name">
                                    <img src="{% static 'img/footer/yeonjin.jpg' %}" width="100" height="100" alt="yeonjin">
                                    <p class="pt-2 text-center" style="font-family:'LotteMartHappy';">김연진</p>
                                </a>
                            </li>
                            <li>
                                <a href="https://github.com/khj6165" target="_blank" class="developers-name">
                                    <img src="{% static 'img/footer/hyojeong.jpg' %}" width="100" height="100" alt="hyojeong">
                                    <p class="pt-2 text-center" style="font-family:'LotteMartHappy';">김효정</p>
                                </a>
                            </li>
                            <li>
                                <a href="https://github.com/JuYeong0413" target="_blank" class="developers-name">
                                    <img src="{% static 'img/footer/juyeong.png' %}" width="100" height="100" alt="juyeong">
                                    <p class="pt-2 text-center" style="font-family:'LotteMartHappy';">이주영</p>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="footer-bottom">
        <div class="container">
            <div class="row d-flex">
                <p class="col-lg-12 footer-text text-center">Copyright &copy; LOHB'S Pick 2020 All rights reserved &nbsp; | &nbsp; <a href="{% url 'service_terms' %}">이용약관</a>&nbsp; <a href="{% url 'personal_data' %}">개인정보처리방침</a></p>
            </div>
        </div>
    </div>
</footer>
<!--================ End footer Area  =================-->

templates/shared/_navbar.html
 {% load static %}
 
 <!--================ Start Header Menu Area =================-->
 <header class="header_area" style="z-index: 999;">
    <div class="main_menu">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <a class="navbar-brand logo_h" href="{% url 'main' %}"><img src="{% static 'img/log.png' %}" width="150px" height="45px" alt=""></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <div class="collapse navbar-collapse offset" id="navbarSupportedContent">
            <ul class="nav navbar-nav menu_nav ml-auto mr-auto">
              <li class="nav-item"><a class="nav-link" href="{% url 'main' %}">Home</a></li>
              <li class="nav-item"><a class="nav-link" href="{% url 'products:main' %}">Products</a></li>
              <li class="nav-item submenu dropdown">
                <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Lohbs' pick</a>
                <ul class="dropdown-menu">
                  {% if user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'picks:lohbs_pick' %}">My pick</a></li>
                  {% endif %}
                  <li class="nav-item"><a class="nav-link" href="{% url 'picks:shared' %}">Shared</a></li>
                </ul>
			        </li>
              {% if user.is_authenticated %}
                <li class="nav-item"><a class="nav-link" href="{% url 'orders:main' %}">Orders</a></li>
                <li class="nav-item submenu dropdown">
                  <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Mypage</a>
                  <ul class="dropdown-menu">
                    <li class="nav-item"><a class="nav-link" href="{% url 'users:main' user.id %}">My info</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'users:schedule' user.id %}">Schedule</a></li>
                  </ul>
                </li>
              {% endif %}
              {% if user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'account_logout' %}" style="color:black;"> Logout</a></li>
                {% else %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'account_login' %}" style="color:black;"> Login</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'account_signup' %}" style="color:black;"> Sign up</a></li>
                {% endif %}
            </ul>

                
          </div>
        </div>
      </nav>
    </div>
  </header>
    <!--================ End Header Menu Area =================-->