lohbs_pick/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.main, name="main"),
    path('accounts/', include('allauth.urls')),
    path('users/', include('users.urls')),
    path('products/', include('products.urls')),
    path('picks/', include('picks.urls')),
    path('orders/', include('orders.urls')),
    path('personal_data/', views.personal_data, name="personal_data"),
    path('service_terms/', views.service_terms, name="service_terms"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

picks/urls.py
from django.urls import path
from . import views

app_name ="picks"
urlpatterns = [
    path('lohbs_pick/', views.lohbs_pick, name="lohbs_pick"),
    path('delete/<int:collection_id>/', views.delete, name="delete"),
    path('delete_cp/<int:cp_id>/<int:collection_id>/', views.delete_cp, name="delete_cp"),
    path('collection_add/', views.collection_add, name="collection_add"),
    path('create_cp/<int:product_id>/', views.create_cp, name="create_cp"),
    path('collection_update/<int:collection_id>/', views.collection_update, name="collection_update"),

    ## 공유 관련
    path('shared/', views.shared, name="shared"),
    path('<int:collection_id>/share/', views.share_new, name="share_new"),
    path('create/', views.share_create, name="share_create"),
    path('<int:id>/edit/', views.share_edit, name="share_edit"),
    path('<int:id>/update/', views.share_update, name="share_update"),
    path('<int:id>/delete/', views.share_delete, name="share_delete"),
]

products/urls.py
from django.urls import path
from . import views

app_name ="products"
urlpatterns = [
    path('', views.main, name="main"),
    path('search/', views.search, name="search"),
    path('category_list/', views.category_list, name="category_list"),
    # path('collection_add/<int:product_id>/<int:collection_id>/', views.collection_add, name="collection_add"),
]

products/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _

class Product(models.Model):
    PRODUCT_KIND_CHOICES = [
        (0, "스킨케어"),
        (1, "메이크업"),
        (2, "헤어케어"),
        (3, "바디케어"),
        (4, "향수/방향"),
        (5, "리빙/잡화"),
        (6, "맨케어"),
        (7, "헬스"),
        (8, "푸드"),
        (9, "베이비케어"),
        (10, "펫케어"),
    ]   

    brand = models.CharField(_('브랜드명'), max_length=100) 
    name = models.CharField(_('상품명'),max_length=100)
    price = models.PositiveIntegerField(_('상품가격'))
    image = models.ImageField(_('상품이미지'),upload_to='product_images/')
    category = models.PositiveSmallIntegerField(_('상품종류'), choices = PRODUCT_KIND_CHOICES)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

products/views.py
from django.shortcuts import render,get_object_or_404
from django.db.models import Count
from .models import Product
import pdb, collections, json
from picks.models import Collection
from picks.models import *
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

def main(request):
    sort = request.GET.get('sort', '')

    if sort == "lowPrice":
        product_list = Product.objects.all().order_by('price')  
    elif sort == "highPrice":
        product_list = Product.objects.all().order_by('-price')
    elif sort == "popular":
        product_list = Product.objects.all().annotate(num_cps=Count('collectionproduct')).order_by('-num_cps') 
    else:
        product_list = Product.objects.all().order_by('-id')

    category_no = collections.defaultdict(int)
    for i in range(0, 11):
        category_no[str(i)] = len(Product.objects.filter(category=i))

    # pagination
    page = request.GET.get('page', 1)
    paginator = Paginator(product_list, 21)
    try:
        products = paginator.get_page(page)
    except PageNotAnInteger:
        products = paginator.page(1)
    except EmptyPage:
        products = paginator.page(paginator.num_pages)

    if request.user.is_active:
        lists = Collection.objects.filter(user=request.user)
        return render(request, 'products/main.html', {'products':products, 'category_no':category_no, 'lists':lists})

    return render(request, 'products/main.html', {'products':products, 'category_no':category_no})


def search(request):
    sort = request.GET.get('sort', '')
    query = request.GET.get('query', '')

    if sort=="lowPrice":
        search_products = Product.objects.filter(name__contains=query).order_by('price')  
    elif sort =="highPrice":
        search_products = Product.objects.filter(name__contains=query).order_by('-price')
    else:
        search_products = Product.objects.filter(name__contains=query).annotate(num_cps=Count('collectionproduct')).order_by('-num_cps') 

    category_no = collections.defaultdict(int)
    for i in range(0, 11):
        category_no[str(i)] = len(Product.objects.filter(category=i))
    
    if request.user.is_active:
        lists = Collection.objects.filter(user=request.user)
        return render(request, 'products/search.html', {'search_products':search_products, 'query':query, 'category_no':category_no, 'lists':lists})
    
    return render(request, 'products/search.html', {'search_products':search_products, 'query':query, 'category_no':category_no})

def category_list(request):
    sort = request.GET.get('sort', '')
    category = request.GET.get('category', '')
    category = int(category)
    
    if sort=="lowPrice":
        category_lists = Product.objects.filter(category=category).order_by('price')  
    elif sort =="highPrice":
        category_lists = Product.objects.filter(category=category).order_by('-price')
    else:
        category_lists = Product.objects.filter(category=category).annotate(num_cps=Count('collectionproduct')).order_by('-num_cps') 

    category_no = collections.defaultdict(int)
    for i in range(0, 11):
        category_no[str(i)] = len(Product.objects.filter(category=i))
    
    if request.user.is_active:
        lists = Collection.objects.filter(user=request.user)
        return render(request, 'products/category_list.html', {'category_lists':category_lists, 'output':category, 'category_no':category_no, 'lists':lists})
    
    return render(request, 'products/category_list.html', {'category_lists':category_lists, 'output':category, 'category_no':category_no})

products/templates/products/category_list.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% block content %}

<link rel="stylesheet" href="{% static 'css/pick-shared.css' %}">
<link rel="stylesheet" href="{% static 'css/breadcrumb.css' %}">

	<!-- ================ start banner area ================= -->	
  <section class="blog-banner-area" id="category">
    <div class="container h-100">
      <div class="blog-banner">
        <div class="text-center breadcrumb-content" style="margin-top: 0;">
          <h2 class="page-title">Shop Category</h2>
          <nav aria-label="breadcrumb" class="banner-breadcrumb">
            <ol class="breadcrumb justify-content-center">
              <li class="breadcrumb-item"><a href="{% url 'main' %}"><i class="fas fa-home"></i> Home</a></li>
              <li class="breadcrumb-item active" aria-current="page">Shop Category</li>
            </ol>
          </nav>
        </div>
      </div>
    </div>
  </section>
	<!-- ================ end banner area ================= -->


	<!-- ================ category section start ================= -->		  
  <section class="section-margin--small mb-5">
    <div class="container">
      <div class="row">
        <div class="col-xl-3 col-lg-4 col-md-5">
          <div class="sidebar-filter mt-0">
            <div class="top-filter-head"><a href="{% url 'products:main' %}" style="color:white; font-family:'LotteMartHappy';">ALL Products</a></div>
              <ul class="main-categories">
                <li class="common-filter" style="padding-top:25px;">
                  <form action="{% url 'products:category_list' %}">
                    <ul>
                      <li class="filter-list"><input class="pixel-radio" type="radio" id="skincare" name="category" value="0" onclick="this.form.submit()"><label for="skincare">스킨케어<span> ({{ category_no.0 }})</span></label></li>
                      <li class="filter-list"><input class="pixel-radio" type="radio" id="makeup" name="category" value="1" onclick="this.form.submit()"><label for="makeup">메이크업 <span> ({{ category_no.1 }})</span></li>
                      <li class="filter-list"><input class="pixel-radio" type="radio" id="haircare" name="category" value="2" onclick="this.form.submit()"><label for="haircare">헤어케어 <span> ({{ category_no.2 }})</span></label></li>
                      <li class="filter-list"><input class="pixel-radio" type="radio" id="bodycare" name="category" value="3" onclick="this.form.submit()"><label for="bodycare">바디케어 <span> ({{ category_no.3 }})</span></label></li>
                      <li class="filter-list"><input class="pixel-radio" type="radio" id="perfume" name="category" value="4" onclick="this.form.submit()"><label for="perfume">향수/방향 <span> ({{ category_no.4 }})</span></label></li>
                      <li class="filter-list"><input class="pixel-radio" type="radio" id="living" name="category" value="5" onclick="this.form.submit()"><label for="living">리빙/잡화 <span> ({{ category_no.5 }})</span></label></li>
                      <li class="filter-list"><input class="pixel-radio" type="radio" id="mencare" name="category" value="6" onclick="this.form.submit()"><label for="mencare">맨케어 <span> ({{ category_no.6 }})</span></label></li>
                      <li class="filter-list"><input class="pixel-radio" type="radio" id="health" name="category" value="7" onclick="this.form.submit()"><label for="helath">헬스 <span> ({{ category_no.7 }})</span></label></li>
                      <li class="filter-list"><input class="pixel-radio" type="radio" id="food" name="category" value="8" onclick="this.form.submit()"><label for="food">푸드 <span> ({{ category_no.8 }})</span></label></li>
                      <li class="filter-list"><input class="pixel-radio" type="radio" id="babycare" name="category" value="9" onclick="this.form.submit()"><label for="babycare">베이비케어 <span> ({{ category_no.9 }})</span></label></li>
                      <li class="filter-list"><input class="pixel-radio" type="radio" id="petcare" name="category" value="10" onclick="this.form.submit()"><label for="petcare">펫케어 <span> ({{ category_no.10 }})</span></label></li>
                    </ul>
                  </form>
                </li>
              </ul>
          </div>
        </div>
        <div class="col-xl-9 col-lg-8 col-md-7">
          <!-- Start Filter Bar -->
          <div class="filter-bar d-flex flex-wrap align-items-center">
            <div class="sorting mr-auto">
              <select id="sort-select" onchange="location = this.value;">
                {% if "/?sort=lowPrice" in request.get_full_path %}
                  <option class="sort-popluar" value="?sort=popluar&category={{output}}">인기순</option>
                  <option class="sort-lowprice" value="?sort=lowPrice" selected>낮은 가격순</option>
                  <option class="sort-highprice" value="?sort=highPrice&category={{output}}">높은 가격순</option>
                {% elif "/?sort=highPrice" in request.get_full_path %}
                  <option class="sort-popluar" value="?sort=popluar&category={{output}}">인기순</option>
                  <option class="sort-lowprice" value="?sort=lowPrice&category={{output}}">낮은 가격순</option>
                  <option class="sort-highprice" value="?sort=highPrice" selected>높은 가격순</option>
                {% else %}
                  <option class="sort-popluar" value="?sort=popluar" selected>인기순</option>
                  <option class="sort-lowprice" value="?sort=lowPrice&category={{output}}">낮은 가격순</option>
                  <option class="sort-highprice" value="?sort=highPrice&category={{output}}">높은 가격순</option>
                {% endif %}
              </select>
            </div>
            <div>
              <form action="{% url 'products:search' %}">
                <div class="input-group filter-bar-search">
                    <input type="text" placeholder="Search" name="query">
                    <div class="input-group-append">
                      <button type="submit"><i class="ti-search"></i></button>
                    </div>
                </div>
              </form>
            </div>
          </div>
          <!-- End Filter Bar -->
          
          <!-- Start Best Seller -->
          <section class="lattest-product-area pb-40 category-list">
            <div class="row">
              {% for product in category_lists %}
                <div class="col-md-6 col-lg-4">
                  <div class="card text-center card-product">
                    <div class="card-product__img">
                      <img class="card-img" src="{{ product.image.url }}" alt="">
                      <ul class="card-product__imgOverlay">
                        <li>
                          <button id="btnid" type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalCenter{{ forloop.counter0 }}">
                            <i class="fas fa-plus"></i>
                          </button>
                        </li>
                      </button>
                      </ul>
                    </div>
                    <div class="card-body">
                      <p>{{ product.brand }}</p>
                      <h6 class="card-product__title">{{ product.name }}</h6>
                      <p class="card-product__price" style="display: inline;">{{ product.price| intcomma }}</p>
                      <p style="display:inline; font-size:14px;">원</p>
                    </div>
                  </div>
                </div>
              {% endfor %}
            </div>
          </section>
          <!-- End Best Seller -->
        </div>
      </div>
    </div>
  </section>
  <!-- ================ category section end ================= -->		  
 
  {% for product in category_lists %}
    <!-- Modal -->
    <div class="modal fade" id="exampleModalCenter{{forloop.counter0}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLongTitle">롭스픽 선택하기</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <form action="{% url 'picks:create_cp' product.id %}" method="POST">
              <div class="modal-body">
                {% csrf_token %}
                <div class="mb-2 container">
                  <label>수량:&nbsp;</label>
                  <div class="product_count">
                    <input type="text" name="quantity" id="sst{{ forloop.counter0 }}" maxlength="12" value="1" title="Quantity:" class="input-text qty" style="width:50px;height:30px;">
                    <button onclick="var result = document.getElementById('sst{{ forloop.counter0 }}'); var sst{{ forloop.counter0 }} = result.value; if( !isNaN( sst{{ forloop.counter0 }} )) result.value++;return false;" class="increase items-count" type="button"><i class="fas fa-chevron-up"></i></button>
                    <button onclick="var result = document.getElementById('sst{{ forloop.counter0 }}'); var sst{{ forloop.counter0 }} = result.value; if( !isNaN( sst{{ forloop.counter0 }} ) &amp;&amp; sst{{ forloop.counter0 }} > 1 ) result.value--;return false;" class="reduced items-count" type="button"><i class="fas fa-chevron-down"></i></button>
                  </div>
                </div>
                <div class="container">
                  <label><strong><컬렉션 목록></strong></label>
                  <br>
                  <!-- <input class="pixel-radio" type="radio" name="new"> 새 컬렉션 만들기 -->
                  {% for pick in lists %}
                    <input class="pixel-radio" type="radio" name="pick" value="{{pick.id}}" style="margin-right:5px;">{{pick.name}}<br>
                  {% endfor %}
                    <input class="pixel-radio" type="radio" name="pick" style="margin-right:5px;" value="new">새로운 컬렉션 생성:&nbsp; <input type="text" name="collection_name">
                </div>
              </div>
            <div class="modal-footer">
              <button type="submit" class="btn btn-primary">저장</button>
            </div>
        </form>
        </div>
      </div>
    </div>
  {% endfor %}
  <!-- Modal -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.3/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
  <script>
      let temp = {{ output }};
      $(":radio[name='category']").each(function() {
          var $this = $(this);
          if($this.val() == temp)
              $this.attr('checked', true);
      });
  </script>
  {% endblock %}

products/templates/products/main.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% block content %}

<link rel="stylesheet" href="{% static 'css/breadcrumb.css' %}">
<link rel="stylesheet" href="{% static 'css/pick-shared.css' %}">

<!-- ================ start banner area ================= -->	
<section class="blog-banner-area" id="category">
  <div class="container h-100">
    <div class="blog-banner">
      <div class="text-center breadcrumb-content" style="margin-top: 0;">
        <h2 class="page-title">Shop Category</h2>
        <nav aria-label="breadcrumb" class="banner-breadcrumb">
          <ol class="breadcrumb justify-content-center">
            <li class="breadcrumb-item"><a href="{% url 'main' %}"><i class="fas fa-home"></i> Home</a></li>
            <li class="breadcrumb-item active" aria-current="page">Shop Category</li>
          </ol>
        </nav>
      </div>
    </div>
  </div>
</section>
<!-- ================ end banner area ================= -->

<!-- ================ category section start ================= -->		  
  <section class="section-margin--small mb-5">
    <div class="container">
      <div class="row">
        <div class="col-xl-3 col-lg-4 col-md-5">
          
          <div class="sidebar-filter mt-0">
            <div class="top-filter-head"><a href="{% url 'products:main' %}" style="color:white;font-family:'LotteMartHappy;'">ALL Products</a></div>
              <ul class="main-categories">
                <li class="common-filter" style="padding-top:25px;">
                  <form action="{% url 'products:category_list' %}">
                    <ul>
                      <li class="filter-list"><input class="pixel-radio" type="radio" id="skincare" name="category" value="0" onclick="this.form.submit()"><label for="skincare">스킨케어<span> ({{ category_no.0 }})</span></label></li>
                      <li class="filter-list"><input class="pixel-radio" type="radio" id="makeup" name="category" value="1" onclick="this.form.submit()"><label for="makeup">메이크업 <span> ({{ category_no.1 }})</span></li>
                      <li class="filter-list"><input class="pixel-radio" type="radio" id="haircare" name="category" value="2" onclick="this.form.submit()"><label for="haircare">헤어케어 <span> ({{ category_no.2 }})</span></label></li>
                      <li class="filter-list"><input class="pixel-radio" type="radio" id="bodycare" name="category" value="3" onclick="this.form.submit()"><label for="bodycare">바디케어 <span> ({{ category_no.3 }})</span></label></li>
                      <li class="filter-list"><input class="pixel-radio" type="radio" id="perfume" name="category" value="4" onclick="this.form.submit()"><label for="perfume">향수/방향 <span> ({{ category_no.4 }})</span></label></li>
                      <li class="filter-list"><input class="pixel-radio" type="radio" id="living" name="category" value="5" onclick="this.form.submit()"><label for="living">리빙/잡화 <span> ({{ category_no.5 }})</span></label></li>
                      <li class="filter-list"><input class="pixel-radio" type="radio" id="mencare" name="category" value="6" onclick="this.form.submit()"><label for="mencare">맨케어 <span> ({{ category_no.6 }})</span></label></li>
                      <li class="filter-list"><input class="pixel-radio" type="radio" id="health" name="category" value="7" onclick="this.form.submit()"><label for="helath">헬스 <span> ({{ category_no.7 }})</span></label></li>
                      <li class="filter-list"><input class="pixel-radio" type="radio" id="food" name="category" value="8" onclick="this.form.submit()"><label for="food">푸드 <span> ({{ category_no.8 }})</span></label></li>
                      <li class="filter-list"><input class="pixel-radio" type="radio" id="babycare" name="category" value="9" onclick="this.form.submit()"><label for="babycare">베이비케어 <span> ({{ category_no.9 }})</span></label></li>
                      <li class="filter-list"><input class="pixel-radio" type="radio" id="petcare" name="category" value="10" onclick="this.form.submit()"><label for="petcare">펫케어 <span> ({{ category_no.10 }})</span></label></li>
                    </ul>
                  </form>
                </li>
              </ul>
          </div>
       
        </div>
        <div class="col-xl-9 col-lg-8 col-md-7">
          <!-- Start Filter Bar -->
          <div class="filter-bar d-flex flex-wrap align-items-center">
            <div class="sorting mr-auto">
              <select id="sort-select" onchange="location = this.value;">
                {% if "/?sort=lowPrice" in request.get_full_path %}
                  <option class="sort-popluar" value="?sort=popluar">인기순</option>
                  <option class="sort-lowprice" value="?sort=lowPrice" selected>낮은 가격순</option>
                  <option class="sort-highprice" value="?sort=highPrice">높은 가격순</option>
                {% elif "/?sort=highPrice" in request.get_full_path %}
                  <option class="sort-popluar" value="?sort=popluar">인기순</option>
                  <option class="sort-lowprice" value="?sort=lowPrice">낮은 가격순</option>
                  <option class="sort-highprice" value="?sort=highPrice" selected>높은 가격순</option>
                {% else %}
                   <option class="sort-popluar" value="?sort=popluar" selected>인기순</option>
                  <option class="sort-lowprice" value="?sort=lowPrice">낮은 가격순</option>
                  <option class="sort-highprice" value="?sort=highPrice">높은 가격순</option>
                {% endif %}
              </select>
            </div>
            <div>
              <form action="{% url 'products:search' %}">
                <div class="input-group filter-bar-search">
                    <input type="text" placeholder="Search" name="query">
                    <div class="input-group-append">
                      <button type="submit"><i class="ti-search"></i></button>
                    </div>
                </div>
              </form>
            </div>
          </div>
          <!-- End Filter Bar -->
          
          <!-- Start Best Seller -->
          <section class="lattest-product-area pb-40 category-list">
            <div class="row">
              {% for product in products %}
                <div class="col-md-6 col-lg-4">
                  <div class="card text-center card-product">
                    <div class="card-product__img">
                      <img class="card-img" src="{{ product.image.url }}" alt="">
                        <ul class="card-product__imgOverlay">
                            <li>
                              <button id="btnid" type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalCenter{{ forloop.counter0 }}">
                                <i class="fas fa-plus"></i>
                              </button>
                            </li>
                        </ul>
                    </div>
                    <div class="card-body">
                      <p>{{ product.brand }}</p>
                      <h6 class="card-product__title">{{ product.name }}</h6>
                      <p class="card-product__price" style="display: inline;">{{ product.price | intcomma }}</p>
                      <p style="display:inline; font-size:14px;">원</p>
                    </div>
                  </div>
                </div>
              {% endfor %}
            </div>
          </section>
          <!-- End Best Seller -->

          <!-- TODO: Pagination -->
          {% if products.has_other_pages %}
              <div class="pagination">
                  {% if products.has_previous %}
                      <a href="?page={{ products.previous_page_number }}"><i class="fa fa-angle-left"></i></a>
                  {% else %}
                      <a href=""><i class="fa fa-angle-left"></i></a>
                  {% endif %}
                  {% for i in products.paginator.page_range %}
                      {% if products.number == i %}
                          <a href="" class="active">{{ i }}</a>
                      {% else %}
                          <a href="?page={{ i }}">{{ i }}</a>
                      {% endif %}
                  {% endfor %}
                  {% if products.has_next %}
                      <a href="?page={{ products.next_page_number }}"><i class="fa fa-angle-right"></i></a>
                  {% else %}
                      <a href=""><i class="fa fa-angle-right"></i></a>
                  {% endif %}
              </div>
            {% endif %}
            <!-- End Pagination -->

        </div>
      </div>
    </div>
  </section>
  <!-- ================ category section end ================= -->		  
  
  {% for product in products %}
    <!-- Modal -->
    <div class="modal fade" id="exampleModalCenter{{forloop.counter0}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLongTitle">롭스픽 선택하기</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <form action="{% url 'picks:create_cp' product.id %}" method="POST">
              <div class="modal-body">
                {% csrf_token %}
                <div class="mb-2 container">
                  <label>수량:&nbsp;</label>
                  <div class="product_count">
                    <input type="text" name="quantity" id="sst{{ forloop.counter0 }}" maxlength="12" value="1" title="Quantity:" class="input-text qty" style="width:50px;height:30px;">
                    <button onclick="var result = document.getElementById('sst{{ forloop.counter0 }}'); var sst{{ forloop.counter0 }} = result.value; if( !isNaN( sst{{ forloop.counter0 }} )) result.value++;return false;" class="increase items-count" type="button"><i class="fas fa-chevron-up"></i></button>
                    <button onclick="var result = document.getElementById('sst{{ forloop.counter0 }}'); var sst{{ forloop.counter0 }} = result.value; if( !isNaN( sst{{ forloop.counter0 }} ) &amp;&amp; sst{{ forloop.counter0 }} > 1 ) result.value--;return false;" class="reduced items-count" type="button"><i class="fas fa-chevron-down"></i></button>
                  </div>
                </div>
                <div class="container">
                  <label><strong><컬렉션 목록></strong></label>
                  <br>
                  <!-- <input class="pixel-radio" type="radio" name="new"> 새 컬렉션 만들기 -->
                  {% if not lists %}
                    <input class="pixel-radio" type="radio" name="pick" style="margin-right:5px;" value="new" checked>새로운 컬렉션 생성:&nbsp; <input type="text" name="collection_name">
                  {% else %}
                    {% for pick in lists %}
                      <input class="pixel-radio" type="radio" name="pick" value="{{pick.id}}" style="margin-right:5px;">{{pick.name}}<br>
                    {% endfor %}
                      <input class="pixel-radio" type="radio" name="pick" style="margin-right:5px;" value="new">새로운 컬렉션 생성:&nbsp; <input type="text" name="collection_name">
                  {% endif %}
                </div>
              </div>
            <div class="modal-footer">
              <button type="submit" class="button button--active button-review">저장</button>
            </div>
        </form>
        </div>
      </div>
    </div>
  {% endfor %}
{% endblock %}